name: Build and Release
on: push

jobs:
  weasyprint-build:
    name: Build WeasyPrint
    strategy:
      matrix:
        version: ["3.12", "3.13"]
        arch: ["x86_64", "arm64"]
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    env:
      RUNTIME: ${{ matrix.version }}
      ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer 
        run: make build/weasyprint-layer-python${{ matrix.version }}-${{ matrix.arch }}.zip
      - name: Test weasyprint
        run: |
          mkdir output
          make test.start.container &
          sleep 1
          make test.print.report
          rm -rf build/opt
        env:
          TEST_FILENAME: build/test-report-${{ matrix.version }}-${{ matrix.arch }}.pdf 
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WeasyPrint Layer Build ${{ matrix.version }} ${{ matrix.arch }}
          path: build
  weasyprint-release:
    name: Release WeasyPrint
    runs-on: ubuntu-latest
    needs: [weasyprint-build]
    if: startsWith(github.ref, 'refs/tags/weasyprint-')
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create WeasyPrint Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: ./artifacts/**/weasyprint-layer-python*

  ghostscript-build:
    name: Build GhostScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer
        run: |
          make build/ghostscript-layer.zip
          rm -rf build/opt
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: GhostScript Layer Build
          path: build
      - name: Create GhostScript Release
        if: startsWith(github.ref, 'refs/tags/ghostscript-')
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: ./build/ghostscript-layer.zip
